import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { Github, Mail } from "lucide-react";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Header from "./header";
import { ThemeProvider } from "./theme-provider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Test | Nimesh Maharjan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background flex justify-between flex-col font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header></Header>
          <main className="flex-1">{children}</main>
          <footer className="shadow">
            <section className="container py-4 flex items-center justify-between">
              <p className="font-semibold">Nimesh Maharjan</p>
              <div className="flex items-center gap-2">
                <Link href="https://github.com/nimeshmaharjan1">
                  <Button size={"icon"} variant={"outline"}>
                    <Github className="w-4 h-4"></Github>
                  </Button>
                </Link>
                <Link href="mailto:maharjannimesh11@gmail.com">
                  <Button size={"icon"} variant={"outline"}>
                    <Mail className="w-4 h-4"></Mail>
                  </Button>
                </Link>
              </div>
            </section>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
